name: Build JPEG Library for iOS

on:
  workflow_call:
    outputs:
      cache-key:
        description: "Cache key for JPEG build"
        value: ${{ jobs.build-jpeg.outputs.cache-key }}
      artifact-name:
        description: "Artifact name for JPEG build"
        value: ${{ jobs.build-jpeg.outputs.artifact-name }}
  workflow_dispatch:

env:
  IOS_DEPLOYMENT_TARGET: "13.0"

jobs:
  build-jpeg:
    runs-on: macos-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
      artifact-name: jpeg-ios
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version

    - name: Install dependencies
      run: |
        brew install cmake

    - name: Generate cache key
      id: cache-key
      run: |
        echo "key=jpeg-${{ runner.os }}-${{ hashFiles('BuildJPEG/build.sh') }}-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Cache JPEG build
      id: cache-jpeg
      uses: actions/cache@v4
      with:
        path: BuildJPEG/output
        key: ${{ steps.cache-key.outputs.key }}
        restore-keys: |
          jpeg-${{ runner.os }}-

    - name: Build JPEG library
      if: steps.cache-jpeg.outputs.cache-hit != 'true'
      working-directory: BuildJPEG
      run: |
        set -ex
        
        # Clone libjpeg-turbo
        git clone https://github.com/libjpeg-turbo/libjpeg-turbo.git
        WORKDING_DIR="$(pwd)/libjpeg-turbo"
        
        # Check if working dir is all right
        if [ ! -d "$WORKDING_DIR" ]; then
            mkdir -p "$WORKDING_DIR"
        fi
        
        cd "$WORKDING_DIR"
        WORKDING_DIR=$(pwd)
        
        git clean -fdx
        
        # Setup iOS build environment
        IOS_PLATFORMDIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
        IOS_SYSROOT=($IOS_PLATFORMDIR/Developer/SDKs/iPhoneOS.sdk)
        export CFLAGS="-Wall -arch arm64 -miphoneos-version-min=${{ env.IOS_DEPLOYMENT_TARGET }} -funwind-tables"
        
        # Create toolchain file
        cat <<EOF >toolchain.cmake
        set(BUILD_SHARED_LIBS OFF)
        set(CMAKE_SYSTEM_NAME iOS)
        set(CMAKE_SYSTEM_PROCESSOR aarch64)
        set(CMAKE_OSX_DEPLOYMENT_TARGET ${{ env.IOS_DEPLOYMENT_TARGET }})
        set(CMAKE_C_COMPILER /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang)
        EOF
        
        # Configure with CMake
        cmake -G Xcode -B build \
            -DENABLE_SHARED=0 \
            -DCMAKE_INSTALL_PREFIX=${WORKDING_DIR}/../output \
            -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake \
            -DCMAKE_OSX_SYSROOT=${IOS_SYSROOT}
        
        # Build with Xcode
        xcodebuild build \
            -project build/libjpeg-turbo.xcodeproj \
            -scheme ALL_BUILD \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" \
            STRIP_INSTALLED_PRODUCT=NO COPY_PHASE_STRIP=NO UNSTRIPPED_PRODUCT=NO
        
        # Install
        cd build
        ln -s Release-iphoneos Release
        cmake -P cmake_install.cmake

    - name: Verify JPEG build
      run: |
        ls -la BuildJPEG/output/lib/
        ls -la BuildJPEG/output/include/
        echo "JPEG libraries:"
        file BuildJPEG/output/lib/*.a | head -5

    - name: Upload JPEG artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jpeg-ios
        path: BuildJPEG/output/
        retention-days: 1